export default {
  skin: [
    { value: 'meibai', label: '美白' },
    { value: 'bushui', label: '补水' },
    { value: 'queban', label: '祛斑' },
    { value: 'quedou', label: '祛痘' },
    { value: 'hongyansi', label: '红血丝' },
    { value: 'others', label: '其他' },
  ],
  facial: [
    { value: 'quezhou', label: '祛皱' },
    { value: 'longbi', label: '隆鼻' },
    { value: 'fengchun', label: '丰唇' },
    { value: 'xiaba', label: '下巴' },
    { value: 'yanjing', label: '眼睛' },
    { value: 'etou', label: '额头' },
    { value: 'pingguoji', label: '苹果肌' },
    { value: 'taiyangxue', label: '太阳穴' },
    { value: 'yintang', label: '印堂' },
    { value: 'aoxian', label: '凹陷' },
    { value: 'yaoji', label: '咬肌' },
    { value: 'rongzhi', label: '溶脂' },
    { value: 'tishengxiandiao', label: '提升线雕' },
    { value: 'others', label: '其他' },
  ],
  body: [
    { value: 'shoushen', label: '瘦身' },
    { value: 'suxing', label: '塑型' },
    { value: 'kangshuai', label: '抗衰' },
    { value: 'paidu', label: '排毒' },
    { value: 'heermeng', label: '荷尔蒙' },
    { value: 'fangai', label: '防癌' },
    { value: 'daiyun', label: '代孕' },
    { value: 'simihuli', label: '私密护理' },
    { value: 'others', label: '其他' },
  ],
}
